#!/bin/sh

CURRENT="linux-image-`uname -r`"
echo "Current running kernel: $CURRENT"

NEWEST=`dpkg -l | grep linux-image- | egrep '^ii' | awk '{print $2}' | grep "[0-9]\.[0-9]" | sort -V | tail -n1`
echo "Newest installed kernel: $NEWEST"

GENERIC=`dpkg -l linux-image-generic | egrep '^ii' | awk '{print $3}' `
echo "Newest installed generic kernel version: $GENERIC"

TOREMOVE=`dpkg -l | grep linux-image- | egrep '^ii' | awk '{print $2}' | grep "[0-9]\.[0-9]" | sort -V | head -n-1 | grep -v $CURRENT`

HEADERS=`dpkg -l | grep linux-image- | egrep '^ii' | awk '{print $2}' | grep "[0-9]\.[0-9]" | sort -V | head -n-1 | grep -v $CURRENT | sed 's/linux-image-\(.*\)-\(.*\)/linux-headers-\1/'`

echo "To remove:"
for i in $TOREMOVE $HEADERS ; do
  echo "  $i"
done

if [ "$1" = "-y" ]
then
	ARGS="$ARGS -y"
fi

apt-get $ARGS purge $TOREMOVE $HEADERS
